/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *winProc1;
    QLabel *winFinalRes;
    QLabel *winProc2;
    QLabel *winProc3;
    QLabel *winProc4;
    QPushButton *btnLoadVideo;
    QPushButton *btnInitProc;
    QLabel *lblMsg;
    QGroupBox *groupBox;
    QRadioButton *rbCircle;
    QRadioButton *rbRing;
    QLineEdit *numRows;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *numCols;
    QLabel *label_5;
    QLineEdit *centersDistance;
    QLabel *winProc5;
    QLabel *winProc6;
    QLabel *winProc7;
    QLabel *winProc8;
    QLabel *winProc9;
    QLabel *subtitle3;
    QLabel *subtitle2;
    QLabel *subtitle1;
    QLabel *subtitle4;
    QLabel *subtitle5;
    QLabel *subtitle6;
    QLabel *subtitle7;
    QLabel *subtitle8;
    QLabel *subtitle9;
    QLabel *mainTitle;
    QGroupBox *groupBox_2;
    QLabel *label_3;
    QLineEdit *calNumFrames;
    QLabel *label_4;
    QLineEdit *calOutputFile;
    QCheckBox *fixAspectRatio;
    QCheckBox *fixPrincipalPoint;
    QCheckBox *zeroTangentDist;
    QCheckBox *withUndistort;
    QCheckBox *saveCamParams;
    QGroupBox *calibOpts;
    QRadioButton *rbCalibNone;
    QRadioButton *rbCalibOpencv;
    QGroupBox *framesOpts;
    QRadioButton *rbFrmManual;
    QRadioButton *rbFrmIntervals;
    QGroupBox *groupBox_3;
    QLabel *label_6;
    QLineEdit *fileDistance;
    QCheckBox *withDistance;
    QPushButton *btnLoadFileDist;
    QLabel *label_7;
    QLabel *label_8;
    QGroupBox *groupBox_4;
    QLineEdit *leTFrames;
    QLabel *label_9;
    QLabel *label_10;
    QLineEdit *leAnalized;
    QLineEdit *timeExec;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *leAccu;
    QLabel *label_13;
    QLineEdit *leTimeframe;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1683, 886);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        winProc1 = new QLabel(centralWidget);
        winProc1->setObjectName(QString::fromUtf8("winProc1"));
        winProc1->setGeometry(QRect(460, 30, 261, 231));
        winProc1->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc1->setScaledContents(true);
        winFinalRes = new QLabel(centralWidget);
        winFinalRes->setObjectName(QString::fromUtf8("winFinalRes"));
        winFinalRes->setGeometry(QRect(1320, 40, 611, 391));
        winFinalRes->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winFinalRes->setScaledContents(true);
        winProc2 = new QLabel(centralWidget);
        winProc2->setObjectName(QString::fromUtf8("winProc2"));
        winProc2->setGeometry(QRect(750, 30, 261, 231));
        winProc2->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc2->setScaledContents(true);
        winProc3 = new QLabel(centralWidget);
        winProc3->setObjectName(QString::fromUtf8("winProc3"));
        winProc3->setGeometry(QRect(1030, 30, 261, 231));
        winProc3->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc3->setScaledContents(true);
        winProc4 = new QLabel(centralWidget);
        winProc4->setObjectName(QString::fromUtf8("winProc4"));
        winProc4->setGeometry(QRect(460, 310, 261, 231));
        winProc4->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc4->setScaledContents(true);
        btnLoadVideo = new QPushButton(centralWidget);
        btnLoadVideo->setObjectName(QString::fromUtf8("btnLoadVideo"));
        btnLoadVideo->setGeometry(QRect(10, 90, 99, 27));
        btnInitProc = new QPushButton(centralWidget);
        btnInitProc->setObjectName(QString::fromUtf8("btnInitProc"));
        btnInitProc->setEnabled(false);
        btnInitProc->setGeometry(QRect(30, 690, 99, 27));
        lblMsg = new QLabel(centralWidget);
        lblMsg->setObjectName(QString::fromUtf8("lblMsg"));
        lblMsg->setGeometry(QRect(150, 690, 351, 31));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 130, 201, 191));
        QFont font;
        font.setPointSize(10);
        groupBox->setFont(font);
        groupBox->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        rbCircle = new QRadioButton(groupBox);
        rbCircle->setObjectName(QString::fromUtf8("rbCircle"));
        rbCircle->setGeometry(QRect(10, 30, 121, 20));
        rbCircle->setFont(font);
        rbCircle->setChecked(true);
        rbRing = new QRadioButton(groupBox);
        rbRing->setObjectName(QString::fromUtf8("rbRing"));
        rbRing->setGeometry(QRect(10, 50, 121, 20));
        rbRing->setFont(font);
        numRows = new QLineEdit(groupBox);
        numRows->setObjectName(QString::fromUtf8("numRows"));
        numRows->setGeometry(QRect(120, 120, 61, 21));
        numRows->setFont(font);
        numRows->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        numRows->setReadOnly(true);
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 120, 101, 21));
        QFont font1;
        font1.setPointSize(10);
        font1.setBold(true);
        font1.setWeight(75);
        label->setFont(font1);
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(10, 90, 101, 21));
        label_2->setFont(font1);
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        numCols = new QLineEdit(groupBox);
        numCols->setObjectName(QString::fromUtf8("numCols"));
        numCols->setGeometry(QRect(120, 90, 61, 21));
        numCols->setFont(font);
        numCols->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        numCols->setReadOnly(true);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 150, 101, 21));
        label_5->setFont(font1);
        label_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        centersDistance = new QLineEdit(groupBox);
        centersDistance->setObjectName(QString::fromUtf8("centersDistance"));
        centersDistance->setGeometry(QRect(120, 150, 61, 21));
        centersDistance->setFont(font);
        centersDistance->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        centersDistance->setReadOnly(false);
        winProc5 = new QLabel(centralWidget);
        winProc5->setObjectName(QString::fromUtf8("winProc5"));
        winProc5->setGeometry(QRect(740, 310, 261, 231));
        winProc5->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc5->setScaledContents(true);
        winProc6 = new QLabel(centralWidget);
        winProc6->setObjectName(QString::fromUtf8("winProc6"));
        winProc6->setGeometry(QRect(1020, 310, 261, 231));
        winProc6->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc6->setScaledContents(true);
        winProc7 = new QLabel(centralWidget);
        winProc7->setObjectName(QString::fromUtf8("winProc7"));
        winProc7->setGeometry(QRect(470, 590, 261, 231));
        winProc7->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc7->setScaledContents(true);
        winProc8 = new QLabel(centralWidget);
        winProc8->setObjectName(QString::fromUtf8("winProc8"));
        winProc8->setGeometry(QRect(750, 590, 261, 231));
        winProc8->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc8->setScaledContents(true);
        winProc9 = new QLabel(centralWidget);
        winProc9->setObjectName(QString::fromUtf8("winProc9"));
        winProc9->setGeometry(QRect(1030, 590, 261, 231));
        winProc9->setStyleSheet(QString::fromUtf8("border: 1px solid gray;"));
        winProc9->setScaledContents(true);
        subtitle3 = new QLabel(centralWidget);
        subtitle3->setObjectName(QString::fromUtf8("subtitle3"));
        subtitle3->setGeometry(QRect(1030, 10, 261, 17));
        subtitle3->setFont(font1);
        subtitle3->setAlignment(Qt::AlignCenter);
        subtitle2 = new QLabel(centralWidget);
        subtitle2->setObjectName(QString::fromUtf8("subtitle2"));
        subtitle2->setGeometry(QRect(750, 10, 261, 17));
        subtitle2->setFont(font1);
        subtitle2->setAlignment(Qt::AlignCenter);
        subtitle1 = new QLabel(centralWidget);
        subtitle1->setObjectName(QString::fromUtf8("subtitle1"));
        subtitle1->setGeometry(QRect(460, 10, 261, 17));
        subtitle1->setFont(font1);
        subtitle1->setAlignment(Qt::AlignCenter);
        subtitle4 = new QLabel(centralWidget);
        subtitle4->setObjectName(QString::fromUtf8("subtitle4"));
        subtitle4->setGeometry(QRect(460, 290, 261, 17));
        subtitle4->setFont(font1);
        subtitle4->setAlignment(Qt::AlignCenter);
        subtitle5 = new QLabel(centralWidget);
        subtitle5->setObjectName(QString::fromUtf8("subtitle5"));
        subtitle5->setGeometry(QRect(740, 290, 261, 17));
        subtitle5->setFont(font1);
        subtitle5->setAlignment(Qt::AlignCenter);
        subtitle6 = new QLabel(centralWidget);
        subtitle6->setObjectName(QString::fromUtf8("subtitle6"));
        subtitle6->setGeometry(QRect(1020, 290, 261, 17));
        subtitle6->setFont(font1);
        subtitle6->setAlignment(Qt::AlignCenter);
        subtitle7 = new QLabel(centralWidget);
        subtitle7->setObjectName(QString::fromUtf8("subtitle7"));
        subtitle7->setGeometry(QRect(470, 570, 261, 17));
        subtitle7->setFont(font1);
        subtitle7->setAlignment(Qt::AlignCenter);
        subtitle8 = new QLabel(centralWidget);
        subtitle8->setObjectName(QString::fromUtf8("subtitle8"));
        subtitle8->setGeometry(QRect(750, 570, 261, 17));
        subtitle8->setFont(font1);
        subtitle8->setAlignment(Qt::AlignCenter);
        subtitle9 = new QLabel(centralWidget);
        subtitle9->setObjectName(QString::fromUtf8("subtitle9"));
        subtitle9->setGeometry(QRect(1030, 570, 261, 17));
        subtitle9->setFont(font1);
        subtitle9->setAlignment(Qt::AlignCenter);
        mainTitle = new QLabel(centralWidget);
        mainTitle->setObjectName(QString::fromUtf8("mainTitle"));
        mainTitle->setGeometry(QRect(1320, 10, 261, 17));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        mainTitle->setFont(font2);
        mainTitle->setAlignment(Qt::AlignCenter);
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 340, 421, 331));
        groupBox_2->setFont(font);
        label_3 = new QLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(10, 130, 71, 21));
        label_3->setFont(font1);
        label_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        calNumFrames = new QLineEdit(groupBox_2);
        calNumFrames->setObjectName(QString::fromUtf8("calNumFrames"));
        calNumFrames->setEnabled(false);
        calNumFrames->setGeometry(QRect(90, 130, 51, 21));
        calNumFrames->setFont(font);
        calNumFrames->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        calNumFrames->setReadOnly(false);
        label_4 = new QLabel(groupBox_2);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(20, 290, 51, 21));
        label_4->setFont(font1);
        label_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        calOutputFile = new QLineEdit(groupBox_2);
        calOutputFile->setObjectName(QString::fromUtf8("calOutputFile"));
        calOutputFile->setEnabled(false);
        calOutputFile->setGeometry(QRect(80, 290, 141, 21));
        calOutputFile->setFont(font);
        calOutputFile->setReadOnly(false);
        fixAspectRatio = new QCheckBox(groupBox_2);
        fixAspectRatio->setObjectName(QString::fromUtf8("fixAspectRatio"));
        fixAspectRatio->setEnabled(false);
        fixAspectRatio->setGeometry(QRect(20, 162, 141, 22));
        fixAspectRatio->setFont(font);
        fixAspectRatio->setChecked(false);
        fixPrincipalPoint = new QCheckBox(groupBox_2);
        fixPrincipalPoint->setObjectName(QString::fromUtf8("fixPrincipalPoint"));
        fixPrincipalPoint->setEnabled(false);
        fixPrincipalPoint->setGeometry(QRect(20, 187, 141, 22));
        fixPrincipalPoint->setFont(font);
        fixPrincipalPoint->setChecked(false);
        zeroTangentDist = new QCheckBox(groupBox_2);
        zeroTangentDist->setObjectName(QString::fromUtf8("zeroTangentDist"));
        zeroTangentDist->setEnabled(false);
        zeroTangentDist->setGeometry(QRect(20, 212, 141, 22));
        zeroTangentDist->setFont(font);
        zeroTangentDist->setChecked(true);
        withUndistort = new QCheckBox(groupBox_2);
        withUndistort->setObjectName(QString::fromUtf8("withUndistort"));
        withUndistort->setEnabled(false);
        withUndistort->setGeometry(QRect(20, 260, 121, 22));
        saveCamParams = new QCheckBox(groupBox_2);
        saveCamParams->setObjectName(QString::fromUtf8("saveCamParams"));
        saveCamParams->setEnabled(false);
        saveCamParams->setGeometry(QRect(20, 240, 151, 22));
        calibOpts = new QGroupBox(groupBox_2);
        calibOpts->setObjectName(QString::fromUtf8("calibOpts"));
        calibOpts->setGeometry(QRect(10, 30, 151, 81));
        rbCalibNone = new QRadioButton(calibOpts);
        rbCalibNone->setObjectName(QString::fromUtf8("rbCalibNone"));
        rbCalibNone->setGeometry(QRect(10, 20, 121, 22));
        rbCalibNone->setFont(font);
        rbCalibNone->setChecked(true);
        rbCalibOpencv = new QRadioButton(calibOpts);
        rbCalibOpencv->setObjectName(QString::fromUtf8("rbCalibOpencv"));
        rbCalibOpencv->setGeometry(QRect(10, 40, 121, 22));
        rbCalibOpencv->setFont(font);
        framesOpts = new QGroupBox(groupBox_2);
        framesOpts->setObjectName(QString::fromUtf8("framesOpts"));
        framesOpts->setEnabled(false);
        framesOpts->setGeometry(QRect(210, 30, 131, 85));
        rbFrmManual = new QRadioButton(framesOpts);
        rbFrmManual->setObjectName(QString::fromUtf8("rbFrmManual"));
        rbFrmManual->setGeometry(QRect(10, 20, 117, 22));
        rbFrmManual->setChecked(true);
        rbFrmIntervals = new QRadioButton(framesOpts);
        rbFrmIntervals->setObjectName(QString::fromUtf8("rbFrmIntervals"));
        rbFrmIntervals->setGeometry(QRect(10, 40, 117, 22));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setEnabled(false);
        groupBox_3->setGeometry(QRect(70, 820, 271, 101));
        groupBox_3->setFont(font);
        label_6 = new QLabel(groupBox_3);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 60, 67, 21));
        label_6->setFont(font1);
        fileDistance = new QLineEdit(groupBox_3);
        fileDistance->setObjectName(QString::fromUtf8("fileDistance"));
        fileDistance->setEnabled(false);
        fileDistance->setGeometry(QRect(68, 60, 161, 21));
        fileDistance->setFont(font);
        fileDistance->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        fileDistance->setReadOnly(true);
        withDistance = new QCheckBox(groupBox_3);
        withDistance->setObjectName(QString::fromUtf8("withDistance"));
        withDistance->setGeometry(QRect(10, 30, 221, 21));
        withDistance->setFont(font);
        btnLoadFileDist = new QPushButton(groupBox_3);
        btnLoadFileDist->setObjectName(QString::fromUtf8("btnLoadFileDist"));
        btnLoadFileDist->setEnabled(false);
        btnLoadFileDist->setGeometry(QRect(228, 60, 21, 21));
        btnLoadFileDist->setFont(font);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 20, 231, 16));
        label_7->setBaseSize(QSize(5, 0));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Loma"));
        font3.setBold(true);
        font3.setWeight(75);
        label_7->setFont(font3);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 40, 491, 31));
        label_8->setBaseSize(QSize(5, 0));
        label_8->setFont(font3);
        groupBox_4 = new QGroupBox(centralWidget);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(220, 129, 221, 201));
        groupBox_4->setFont(font);
        leTFrames = new QLineEdit(groupBox_4);
        leTFrames->setObjectName(QString::fromUtf8("leTFrames"));
        leTFrames->setGeometry(QRect(120, 30, 91, 23));
        leTFrames->setAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        leTFrames->setReadOnly(true);
        label_9 = new QLabel(groupBox_4);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(20, 30, 101, 21));
        QFont font4;
        font4.setBold(true);
        font4.setWeight(75);
        label_9->setFont(font4);
        label_10 = new QLabel(groupBox_4);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(20, 50, 91, 20));
        label_10->setFont(font4);
        leAnalized = new QLineEdit(groupBox_4);
        leAnalized->setObjectName(QString::fromUtf8("leAnalized"));
        leAnalized->setGeometry(QRect(120, 53, 91, 20));
        leAnalized->setAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        leAnalized->setReadOnly(true);
        timeExec = new QLineEdit(groupBox_4);
        timeExec->setObjectName(QString::fromUtf8("timeExec"));
        timeExec->setGeometry(QRect(120, 130, 91, 21));
        QFont font5;
        font5.setPointSize(11);
        font5.setBold(true);
        font5.setWeight(75);
        timeExec->setFont(font5);
        timeExec->setAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        timeExec->setReadOnly(true);
        label_11 = new QLabel(groupBox_4);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(20, 70, 91, 20));
        label_11->setFont(font4);
        label_12 = new QLabel(groupBox_4);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(20, 120, 91, 31));
        label_12->setFont(font5);
        leAccu = new QLineEdit(groupBox_4);
        leAccu->setObjectName(QString::fromUtf8("leAccu"));
        leAccu->setGeometry(QRect(120, 100, 91, 23));
        leAccu->setAlignment(Qt::AlignJustify|Qt::AlignVCenter);
        leAccu->setReadOnly(true);
        label_13 = new QLabel(groupBox_4);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(18, 100, 81, 20));
        label_13->setFont(font4);
        leTimeframe = new QLineEdit(groupBox_4);
        leTimeframe->setObjectName(QString::fromUtf8("leTimeframe"));
        leTimeframe->setGeometry(QRect(120, 74, 91, 21));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1683, 22));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Camera Calibration", nullptr));
        winProc1->setText(QString());
        winFinalRes->setText(QString());
        winProc2->setText(QString());
        winProc3->setText(QString());
        winProc4->setText(QString());
        btnLoadVideo->setText(QApplication::translate("MainWindow", "Load Video", nullptr));
        btnInitProc->setText(QApplication::translate("MainWindow", "Start", nullptr));
        lblMsg->setText(QString());
        groupBox->setTitle(QApplication::translate("MainWindow", "Patr\303\263n", nullptr));
        rbCircle->setText(QApplication::translate("MainWindow", "Patr\303\263n circular", nullptr));
        rbRing->setText(QApplication::translate("MainWindow", "Patr\303\263n anillo", nullptr));
        label->setText(QApplication::translate("MainWindow", "N\302\260 elems/col:", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "N\302\260 columnas:", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Distancia (mm):", nullptr));
        winProc5->setText(QString());
        winProc6->setText(QString());
        winProc7->setText(QString());
        winProc8->setText(QString());
        winProc9->setText(QString());
        subtitle3->setText(QString());
        subtitle2->setText(QString());
        subtitle1->setText(QString());
        subtitle4->setText(QString());
        subtitle5->setText(QString());
        subtitle6->setText(QString());
        subtitle7->setText(QString());
        subtitle8->setText(QString());
        subtitle9->setText(QString());
        mainTitle->setText(QApplication::translate("MainWindow", "RESULTADO FINAL", nullptr));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Calibraci\303\263n", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "N\302\260 frames:", nullptr));
        calNumFrames->setText(QApplication::translate("MainWindow", "25", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Salida:", nullptr));
        calOutputFile->setText(QApplication::translate("MainWindow", "output.xml", nullptr));
        fixAspectRatio->setText(QApplication::translate("MainWindow", "Fix Aspect Ratio", nullptr));
        fixPrincipalPoint->setText(QApplication::translate("MainWindow", "Fix Principal Point", nullptr));
        zeroTangentDist->setText(QApplication::translate("MainWindow", "Zero Tangent Dist", nullptr));
        withUndistort->setText(QApplication::translate("MainWindow", "Usar undistort", nullptr));
        saveCamParams->setText(QApplication::translate("MainWindow", "Guardar par\303\241metros", nullptr));
        calibOpts->setTitle(QApplication::translate("MainWindow", "Tipo calibraci\303\263n", nullptr));
        rbCalibNone->setText(QApplication::translate("MainWindow", "No calibrar", nullptr));
        rbCalibOpencv->setText(QApplication::translate("MainWindow", "Calib. OpenCV", nullptr));
        framesOpts->setTitle(QApplication::translate("MainWindow", "Selecci\303\263n frames", nullptr));
        rbFrmManual->setText(QApplication::translate("MainWindow", "Manual", nullptr));
        rbFrmIntervals->setText(QApplication::translate("MainWindow", "Por intervalos", nullptr));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Distancia", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Archivo:", nullptr));
        fileDistance->setText(QString());
        withDistance->setText(QApplication::translate("MainWindow", "Calcular distancia a c\303\241mara", nullptr));
        btnLoadFileDist->setText(QApplication::translate("MainWindow", "...", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "CALIBRATION OF CAMERA", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "COMPUTER SCIENCIE UNIVERSITY CATOLICA SAN PABLO", nullptr));
        groupBox_4->setTitle(QApplication::translate("MainWindow", " Time Accuracy", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Total frames :", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Analizados :", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "time/frame :", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "Time AVG: ", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "Accuracy %:", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
